services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  service:
    build: ./
    depends_on:
      - db
    environment:
      PG_ADDR: db:5432
      PG_USER: user
      PG_PASSWORD: password
      PG_APP_NAME: railway
    ports:
      - "8080:8080"

volumes:
  db-data: